#!/usr/bin/env python3
"""Turn Google Takeout saved-list CSVs into shared/maps-places.js.

Usage:  python3 tools/build_maps_places.py "~/Downloads/Gespeichert"

Each CSV in the folder is one Google saved list. The file name is the key
(Milan.csv -> "milan"); a trailing year is dropped ("Lisbon 2021" -> "lisbon").
Google gives us a name and a Maps URL, nothing else - no category, no city
field - so nothing here guesses a type. The places are handed to the
researcher as "these are Nicole's saved places", which is all they need to be.
"""
import csv, json, os, re, sys, glob

# Lists that are wishlists or scratch, not a destination. Kept out of the
# lookup so they can never match a trip; nothing is lost, they are still
# in the CSVs.
SKIP = {"bilder", "standardliste", "standardliste(1)", "standardliste(2)",
        "reiseziele", "around the world", "gespeicherte orte"}

def city_key(filename):
    stem = os.path.splitext(os.path.basename(filename))[0]
    stem = re.sub(r"\s*\d{4}\s*$", "", stem)          # "Lisbon 2021" -> "Lisbon"
    return stem.strip().lower()

def read_list(path):
    """Rows from one CSV. Google sometimes puts a list description and a
    blank line above the header, so the header is found, not assumed."""
    raw = open(path, encoding="utf-8-sig").read().splitlines()
    start = next((i for i, l in enumerate(raw) if l.startswith("Titel,")
                  or l.startswith("Title,")), None)
    if start is None:
        return []
    out = []
    for row in csv.DictReader(raw[start:]):
        name = (row.get("Titel") or row.get("Title") or "").strip()
        if not name:
            continue
        url = (row.get("URL") or "").strip()
        note = " ".join(x.strip() for x in
                        [row.get("Notiz") or row.get("Note") or "",
                         row.get("Kommentar") or row.get("Comment") or ""]
                        if x and x.strip())
        # Google writes this placeholder where a saved pin has no detail.
        if note.startswith("Für diesen gespeicherten Ort"):
            note = ""
        item = {"n": name}
        if url:
            item["u"] = url
        if note:
            item["note"] = note
        out.append(item)
    return out

def main():
    src = os.path.expanduser(sys.argv[1] if len(sys.argv) > 1
                             else "~/Downloads/Gespeichert")
    files = sorted(glob.glob(os.path.join(src, "*.csv")))
    if not files:
        sys.exit("No CSVs found in %s" % src)

    places, skipped, total = {}, [], 0
    for path in files:
        key = city_key(path)
        rows = read_list(path)
        if not rows:
            continue
        if key in SKIP:
            skipped.append((key, len(rows)))
            continue
        bucket = places.setdefault(key, [])
        seen = {p["n"].casefold() for p in bucket}       # same pin in two lists
        for r in rows:
            if r["n"].casefold() in seen:
                continue
            seen.add(r["n"].casefold())
            bucket.append(r)
        total += len(rows)

    body = json.dumps(places, ensure_ascii=False, sort_keys=True,
                      separators=(",", ":"))
    dest = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "shared", "maps-places.js")
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/build_maps_places.py "
                 "from a Google Takeout saved-places export.\n"
                 "   Do not edit by hand - re-run the script instead. */\n")
        fh.write("window.MAPS_PLACES = " + body + ";\n")

    kept = sum(len(v) for v in places.values())
    print("lists kept: %d   places: %d (from %d rows, %d duplicates dropped)"
          % (len(places), kept, total, total - kept))
    for k, n in skipped:
        print("  skipped (not a destination): %s (%d)" % (k, n))
    print("wrote %s (%.1f KB)" % (dest, os.path.getsize(dest) / 1024.0))

if __name__ == "__main__":
    main()
